### ISSUE TITLE
Debug console.log

### ISSUE THREAD

**Issue by jean-emmanuel** [parro-it/electron-localshortcut#12]
There is what seems to be a debug log statement here https://github.com/parro-it/electron-localshortcut/blob/a9543eea4f15b6565a97c249ebebc6fdf0b6f219/index.js#L70 that could be removed.

**Comment by parro-it** [comment]
Thank you, merged your PR

**Comment by jean-emmanuel** [comment]
yay ! 1.1.1 included in https://github.com/jean-emmanuel/open-stage-control :)
