### ISSUE TITLE
Does not respect alternate keyboard layouts?

### ISSUE THREAD

**Issue by chadoh** [parro-it/electron-localshortcut#26]
I'm trying out the [Brave browser](https://brave.com/) and I noticed that it doesn't currently register its keyboard shortcuts correctly. I assume they're busy with all sorts of other things and don't have time to help a picky Dvorak user such as me, so I figured I'd help them out. I'm new to electron but familiar with JS & React & webpack, etc.

## The issue

I use the Dvorak keyboard layout. When I press <kbd>cmd</kbd><kbd>shift</kbd><kbd>]</kbd> to try to switch tabs, Brave-via-electronlocalshortcut looks at the key position rather than the character typed, and instead sends <kbd>cmd</kbd><kbd>shift</kbd><kbd>+</kbd>. I zoom in instead of switching tabs.

## The code

Here's [how they define their shortcuts](https://github.com/brave/browser-laptop/blob/75ffa36130b1ad33c6f311e5e16ed7838b0b50a0/app/localShortcuts.js#L19-L20). Essentially:

``` js
const electronLocalshortcut = require('electron-localshortcut')

module.exports.register = win => {
  electronLocalshortcut.register(win, 'CmdOrCtrl+Shift+]', () => {...})
}
```

## What's wrong?

Is there something that they did wrong, or is this an error in `electron-localshortcut`? Point me in the right direction and I can help fix the issue.

Thanks!

**Comment by parro-it** [comment]
Hi @chadoh, thank you for your detailed issue...

> Is there something that they did wrong, or is this an error in electron-localshortcut? 

Neither... they're using this module right well, and no there's no bug on `electron-localshortcut` side:
I simply pass the shortcut Accelerator parameter to electron globalShortcuts methods, I don't do any changes or traslation to the keycode you passes. 

So I guess you'll have to repost this issue to Electron repo: it's should be his responsibility to interpret keycode Accelerator used.
