### ISSUE TITLE
Cannot find module 'debug'

### ISSUE THREAD

**Issue by Gummibeer** [parro-it/electron-localshortcut#28]
Hey, if I pack my project with this I get an error on execution:

> Uncaught Exception:
> Error: Cannot find module 'debug'
https://github.com/parro-it/electron-localshortcut/blob/master/index.js#L4

This module is in the `devDependencies` but included in the code. So should it be in the `dependencies` or removed or trapped on load like:

```js
try {
    const _debug = require('debug');
    const debug = _debug('electron-localshortcut');
} catch (ex) {
    const debug = function(arg){};
}
```

**Comment by blakef** [comment]
There's a pull request for this #29.

**Comment by parro-it** [comment]
Thank you!
