### ISSUE TITLE
ReRegister shortcut works just after tab-out&in

### ISSUE THREAD

**Issue by Gummibeer** [parro-it/electron-localshortcut#30]
I'm unregister all shortcuts and register them with new callbacks but they are just available after I tab out and back in the window.
So they get unregistered and also registered but arent' useable.

Do you have any idea why or how to solve it?

```js
const shortcut = require('electron-localshortcut');
shortcut.register('CommandOrControl+E', function () {
    screen_edit();
});
shortcut.unregisterAll();
shortcut.register('CommandOrControl+E', function () {
    win.webContents.send('save-img-cfg');
    screen_show();
});
```

**Comment by parro-it** [comment]
That's probably because focus/blur event handlers use the same register function to
reactivate you shortcuts.

What exactly are you trying to accomplish?

**Comment by Gummibeer** [comment]
My usecase is: if the user presses `CTRL+E` it switches to the edit screen in this I will unregister the current listeners and add the new edit-listeners. If the user presses now again `CTRL+E` it switches back to normal view/show mode - so I have to remove all edit listeners and register the show listeners again.
Could be that this is the wrong way to do this - but what's strange is that the old are unregistered and the new are registered but not active until I unfocus and refocus the window. So the new listeners are registered but not active I think!?

**Comment by parro-it** [comment]
@Gummibeer I'll probably have to change how `unregisterAll` works, because it interferes with focus/unfocus behavior in your use case.

> So the new listeners are registered but not active I think!?

That's strange... would you mind to activate debug output and post the output you receive using your app? You have to set DEBUG env variable equal to `electron-localshortcut`.

**Comment by Gummibeer** [comment]
@parro-it sorry, I've reworked it and use IFs now in the listener. And have much to do at work so I can't promise that I can recreate it. :/
