### ISSUE TITLE
unregister() is broken

### ISSUE THREAD

**Issue by Eugeny** [parro-it/electron-localshortcut#35]
It checks `accelerator`, and then calls _unregisterShortcut on `accelerator.accelerator`

**Comment by parro-it** [comment]
Which version are you using?

**Comment by Eugeny** [comment]
The latest one from NPM

**Comment by parro-it** [comment]
It should be 2.0.2, but I cannot find the code you are describe. Could you point the exact version and line on GH?

**Comment by Eugeny** [comment]
accelerator is a string (`typeof win === 'string'`):
https://github.com/parro-it/electron-localshortcut/blob/master/index.js#L218
which then gets fed into _disableShortcut: 
https://github.com/parro-it/electron-localshortcut/blob/master/index.js#L223
where it attempt to use an .accelerator property on the string:
https://github.com/parro-it/electron-localshortcut/blob/master/index.js#L22

**Comment by parro-it** [comment]
Got it, thank you, I'll correct it

**Comment by jianfei** [comment]
When will this be fixed?

Changing https://github.com/parro-it/electron-localshortcut/blob/master/index.js#L223 into `_disableShortcut({ accelerator });` seems fixed this issue.

**Comment by parro-it** [comment]
Could you try with version 3.0.4? The problem should be solved in this last version.
