### ISSUE TITLE
Bug with electron-localshortcut@3.0.2

### ISSUE THREAD

**Issue by cawa-93** [parro-it/electron-localshortcut#38]
The project uses **electron-debug@1.4.0** which includes **electron-localshortcut@3.0.2**
When I start the application, I get an error when I press any key on the keyboard.
![image](https://user-images.githubusercontent.com/1662812/29028332-98a3038e-7b8c-11e7-8076-675219ed3846.png)
When I used the previous version (**electron-debug@1.3.0** + **electron-localshortcut@2.0.2**) of this problem was not observed

**Comment by parro-it** [comment]
Hi @cawa-93, thank you for reporting. 
Could you please check what is the value of `equals` for you? 
It's really strange, because `equals` is a const set to the [keyboardevents-areequal](https://github.com/parro-it/keyboardevents-areequal) module:

```js
const equals = require('keyboardevents-areequal');
```

I suspect it have something to do with webpack. The same issue is reported [here](https://github.com/SimulatedGREG/electron-vue) too and it seem they use webpack to...

**Comment by cawa-93** [comment]
```
 { default: [Function: areEqual] }
```

**Comment by parro-it** [comment]
Seems a problem with es6 modules...

**Comment by cawa-93** [comment]
```js
// ./node_modules\keyboardevents-areequal/index.js
'use strict';

function _lower(key) {
	if (typeof key !== 'string') {
		return key;
	}
	return key.toLowerCase();
}

function areEqual(ev1, ev2) {
	if (ev1 === ev2) {
		// Same object
		// console.log(`Events are same.`)
		return true;
	}

	for (const prop of ['altKey', 'ctrlKey', 'shiftKey', 'metaKey']) {
		const [value1, value2] = [ev1[prop], ev2[prop]];

		if (Boolean(value1) !== Boolean(value2)) {
			// One of the prop is different
			// console.log(`Comparing prop ${prop}: ${value1} ${value2}`);
			return false;
		}
	}

	if ((_lower(ev1.key) === _lower(ev2.key) && ev1.key !== undefined) ||
		(ev1.code === ev2.code && ev1.code !== undefined)) {
		// Events are equals
		return true;
	}

	// Key or code are differents
	// console.log(`key or code are differents. ${ev1.key} !== ${ev2.key} ${ev1.code} !== ${ev2.code}`);

	return false;
}

module.exports = areEqual;
```
I tried to import the module directly into the node environment
```bash
$ node
> const equals = require('keyboardevents-areequal');
undefined
> equals
[Function: areEqual]
```

**Comment by cawa-93** [comment]
For compile I use the [electron-webpack](https://github.com/electron-userland/electron-webpack) from the @develar.

**Comment by parro-it** [comment]
I'm trying to solve the issue by removing "module" property from `keyboardevent-from-electron-accelerator` and `keyboardevents-areequal`  (both sub deps of localshortcut).

But it's strange, I don't understand what I'm doing wrong. As you said, it seems we import a thing using node directly and another using webpack :disappointed:

**Comment by parro-it** [comment]
Could you please remove node_modules folder and retry from scratch? If you can, please check that you are getting `keyboardevent-from-electron-accelerator@0.7.1` and `keyboardevents-areequal@0.2.2`. 

They are now both shipped as es5 only modules

**Comment by develar** [comment]
Just to make clear: electron-webpack include node_modules production as external modules (not included into bundle).

**Comment by cawa-93** [comment]
First I will report: I tried to expose not a function but an object with a method. Looks like it solved the problem.
```
module.exports = {
	areEqual: areEqual
};
```
```
const {areEqual} = require('keyboardevents-areequal');
```

**Comment by parro-it** [comment]
@develar: that's a smart wya for `electron` I think, but it seems indeed we get different exports when using `electron-webpack` vs when not

@cawa-93: yes, I think the issue has to do with `default` exports only. But I prefer to use the default module export when I export just a function, it's more clear and self-explanatory that the module export only a function.

**Comment by cawa-93** [comment]
I test `keyboardevent-from-electron-accelerator@0.7.1` and `keyboardevents-areequal@0.2.2`. No Error

**Comment by parro-it** [comment]
Thank you a lot @cawa-93 :clap:
