### ISSUE TITLE
F12 shortcut is not working

### ISSUE THREAD

**Issue by michaelvtabor** [parro-it/electron-localshortcut#42]
I try to implement opening of the DevTools on F12 press.
My code (main.js):
```
const electronLocalshortcut = require('electron-localshortcut');
electronLocalshortcut.register('F12', function() {
    console.log("F12 pressed!")
});
```
Nothing happened.
Other shortcuts that I tried instead of F12 do work (F11, F3, Ctrl+A and etc.)

**Comment by parro-it** [comment]
Could you try with version 3.0.4? The problem should be solved in this last version.
