### ISSUE TITLE
LocalShortcut in renderer.js

### ISSUE THREAD

**Issue by bhaktigohel** [parro-it/electron-localshortcut#44]
Can I use electron-localshortcut in renderer.js (which is not main file) ???
And if yes, then how ??
I know about remote api of electron but it doesn't work ?

Thanks in advance .

**Comment by chrilith** [comment]
This works for me.

```javascript
import { remote } from 'electron';
import localShorcut from "electron-localshortcut";

localShorcut.register(remote.getCurrentWindow(), "Z", myEventhandler);
```

**Comment by youngyou** [comment]
> This works for me.
> 
> ```js
> import { remote } from 'electron';
> import localShorcut from "electron-localshortcut";
> 
> localShorcut.register(remote.getCurrentWindow(), "Z", myEventhandler);
> ```

I think the the callback will trigger twice after reload.
