### ISSUE TITLE
Accelerator stopped working in v3

### ISSUE THREAD

**Issue by sindresorhus** [parro-it/electron-localshortcut#46]
This used to work in v2, but stopped working in v3:

```js
localShortcut.register('Cmd+Alt+I', () => {
  console.log('Works');
});

Other accelerators like `'Cmd+Shift+C'` work.

**Comment by parro-it** [comment]
Could you try version 3.0.4? It containes an upgraded version of `keyboardevent-from-electron-accelerator` that should solve the problem.

**Comment by sindresorhus** [comment]
Yup, that did it :)
