### ISSUE TITLE
Ctrl+Space is not working

### ISSUE THREAD

**Issue by MuhammedAlkhudiry** [parro-it/electron-localshortcut#79]
my code: 

electronLocalshortcut.register(win, 'Ctrl+Space', () => {
// stuff
});

**Comment by AmagiSakuya** [comment]
I encountered the same problem.'Space' is not working

**Comment by parro-it** [comment]
I fixed the bug in keyboardevent-from-electron-accelerator module.
The version actually in master should be working now. I'll publish a new release soon
