### ISSUE TITLE
Can we enable/disable the shortcut at the renderer process?

### ISSUE THREAD

**Issue by hackjutsu** [parro-it/electron-localshortcut#8]
I want to enable/disable the shortcut based on the status of a UI component, like show or hidden. Is it possible to achieve that on the renderer process?

**Comment by parro-it** [comment]
Yes, it is possible, using [disableallwindow](https://github.com/parro-it/electron-localshortcut#disableallwindow) and  [enableallwindow](https://github.com/parro-it/electron-localshortcut#enableallwindow)

**Comment by parro-it** [comment]
@hackjutsu that solution actually solve your problem?

**Comment by hackjutsu** [comment]
Yep!
