### ISSUE TITLE
unregisterAll(mainWindow) shows error

### ISSUE THREAD

**Issue by JustMe69** [parro-it/electron-localshortcut#80]
Hi,
I'm trying to remove all shortcuts on app.ready.
I'm using electron V5.07 and localshortcut V3.1.0

My code main.js:
```
const { app, BrowserWindow, ipcMain, webContents, session, dialog, globalShortcut } = require('electron');
const localshortcut = require('electron-localshortcut');
const settings = require('electron-settings');
const menu = require('./menu');
const fs = require('fs-extra');

let win, mainWindow, newWindow, sets;

app.on('ready', function() {
    // defines mainWindow
    createMainWindow();

    // and load the index.html of the app.
    mainWindow.loadFile('index.html');

    mainWindow.once('ready-to-show', () => {
        mainWindow.show()
    });

    mainWindow.on('leave-full-screen', () => {
        mainWindow.setAutoHideMenuBar(false);
        mainWindow.setMenuBarVisibility(true);
    });

    mainWindow.on('enter-full-screen', () => {
        mainWindow.setAutoHideMenuBar(true);
        mainWindow.setMenuBarVisibility(false);
    });

    localshortcut.unregisterAll(mainWindow);
});

...

function createMainWindow () {
    // Create the browser window.
    mainWindow = new BrowserWindow({
        width: 1000,
        height: 600,
        closable: false,
        resizable: false,
        autoHideMenuBar: true,
        fullscreenable: true,
        // fullscreen: true,    // @TODO - on production set to true and active
        minimizable: false,
        webPreferences: {
            nodeIntegration: true,
            devTools: true,     // @TODO - on production set to false
            plugins: true,
            webviewTag: true,
            webgl: true,
            webaudio: true
        }
    });

    const menu = require('./menu');

    mainWindow.on('closed', () => {
        mainWindow = null;
    })
}
...
```
The error I get:
![grafik](https://user-images.githubusercontent.com/23456403/61691953-00cbca80-ad2d-11e9-975e-e15b229a236a.png)

What am I doing wrong?
line 42 is:  localshortcut.unregisterAll(mainWindow);

Another question would be - how to disable alt+f4, etc? is it possible? All my tries don't work.

**Comment by LuoRiWuSheng** [comment]
hi ！  I tried to return the electron-localshortcut version.
It will work normally

my test version

   electron @5.0.2 

   electron-localshortcut@2.0.2

**Comment by LuoRiWuSheng** [comment]
> Hi,
> I'm trying to remove all shortcuts on app.ready.
> I'm using electron V5.07 and localshortcut V3.1.0
> 
> My code main.js:
> 
> ```
> const { app, BrowserWindow, ipcMain, webContents, session, dialog, globalShortcut } = require('electron');
> const localshortcut = require('electron-localshortcut');
> const settings = require('electron-settings');
> const menu = require('./menu');
> const fs = require('fs-extra');
> 
> let win, mainWindow, newWindow, sets;
> 
> app.on('ready', function() {
>     // defines mainWindow
>     createMainWindow();
> 
>     // and load the index.html of the app.
>     mainWindow.loadFile('index.html');
> 
>     mainWindow.once('ready-to-show', () => {
>         mainWindow.show()
>     });
> 
>     mainWindow.on('leave-full-screen', () => {
>         mainWindow.setAutoHideMenuBar(false);
>         mainWindow.setMenuBarVisibility(true);
>     });
> 
>     mainWindow.on('enter-full-screen', () => {
>         mainWindow.setAutoHideMenuBar(true);
>         mainWindow.setMenuBarVisibility(false);
>     });
> 
>     localshortcut.unregisterAll(mainWindow);
> });
> 
> ...
> 
> function createMainWindow () {
>     // Create the browser window.
>     mainWindow = new BrowserWindow({
>         width: 1000,
>         height: 600,
>         closable: false,
>         resizable: false,
>         autoHideMenuBar: true,
>         fullscreenable: true,
>         // fullscreen: true,    // @TODO - on production set to true and active
>         minimizable: false,
>         webPreferences: {
>             nodeIntegration: true,
>             devTools: true,     // @TODO - on production set to false
>             plugins: true,
>             webviewTag: true,
>             webgl: true,
>             webaudio: true
>         }
>     });
> 
>     const menu = require('./menu');
> 
>     mainWindow.on('closed', () => {
>         mainWindow = null;
>     })
> }
> ...
> ```
> 
> The error I get:
> ![grafik](https://user-images.githubusercontent.com/23456403/61691953-00cbca80-ad2d-11e9-975e-e15b229a236a.png)
> 
> What am I doing wrong?
> line 42 is: localshortcut.unregisterAll(mainWindow);
> 
> Another question would be - how to disable alt+f4, etc? is it possible? All my tries don't work.

hi ！ I tried to return the electron-localshortcut version.
It will work normally

my test version

electron @5.0.2

electron-localshortcut@2.0.2

**Comment by JustMe69** [comment]
Hi,
so - I should use v".02 of localShortcut?

In short time I will use/upgrade to electron v6
Is localShortcut (V?) compatible with electron version 6?

**Comment by parro-it** [comment]
Fixed this, I'll publish a new release soon
